#DEV enviroment

app:
  message: This is the property file to thr${spring.application.name}  specific to PROD YML Environment

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: <MYSQL_URL>
    username: <USERNAME>
    password: <PASSWORD>
